<div class="hero-unit">
<h1>SimpleFM Skeleton</h1>
<p>This application demonstrates use of the SimpleFM\ZF2 package as the Model layer of a Zend Framework 2 MVC
application, using the FMServer_Sample database as a data provider.</p>
<p><a class="btn btn-primary btn-large" href="https://github.com/soliantconsulting/SimpleFM-skeleton#readme">Learn more &raquo;</a></p>
</div>
<div class="row">
<div class="span5">
<h2>FileMaker Server</h2>
<p>

<?php
if(is_array($this->installMessages)){
    echo '<ul>';
    foreach ($this->installMessages as $message){
        echo '<li>' . $message . '</li>' . PHP_EOL;
    }
    echo '</ul>';
} else {
    echo $this->installMessages . PHP_EOL;
}
?>
        </p>
        <p><a href="http://www.filemaker.com/support/product/documentation.html" class="btn">Documentation &raquo;</a></p>
    </div>
    <div class="span4">
        <h2>SimpleFM</h2>
        <p>SimpleFM version <?php echo \Soliant\SimpleFM\Version::VERSION; ?> is installed.</p>
        <p><a href="https://github.com/soliantconsulting/SimpleFM#simplefm-documentation" class="btn">Documentation &raquo;</a></p>
    </div>
    <div class="span3">
        <h2>Zend Framework</h2>
        <p>Zend Framework version <?php echo \Zend\Version\Version::VERSION; ?> is installed.</p>
        <p><a href="http://packages.zendframework.com/docs/latest/manual/en/index.html" class="btn">Documentation &raquo;</a></p>
    </div>
</div>
    <hr>
<?php if($this->serverIsOnline): ?>

    <div class="row">
        <div class="span5">
            <h2>Congratulations!</h2>
            <p>You have successfully installed the SimpleFM Skeleton application.</p>
        </div>
        <div class="span4">
            <h2>Test Login</h2>
            <p>Try these test credentials:</p>
            <p>username: dave@westsideantiques.com<br>password: dave</p>
        </div>
        <div class="span3">
        <?php 
            $form = $this->form;
            $form->prepare();
            
            echo $this->form()->openTag($form);
            echo $this->formCollection($form);
            echo $this->form()->closeTag();
            
            if ($this->messages){
                echo '<ul>';
                foreach($this->messages as $message)
                {
                    echo '<li>'.$message.'</li>';
                }
                echo '</ul>';
            }
        ?>
        </div>
    </div>
<?php else: ?>
    <div class="row">
        <div class="span12">
        <h2>Install Not Complete</h2>
        <p>Please resolve the Filemaker Server errors.</p>
        </div>
    </div>
<?php endif; ?>
