<div class="hero-unit">
    <h1>SimpleFM FMServer Sample</h1>
    <p>This application demonstrates use of the SimpleFM\ZF2 package as the Model layer of a Zend Framework 2 MVC
    application, using the FMServer_Sample database as a data provider.</p>
    <p><a class="btn btn-primary btn-large" href="https://github.com/soliantconsulting/SimpleFM_FMServer_Sample#readme">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="span5">
        <h2>FileMaker Server</h2>
        <p>
        <?php 
            if(is_array($this->messages)){
                echo '<ul>';
                foreach ($this->messages as $message){
                    echo '<li>' . $message . '</li>' . PHP_EOL;
                }
                echo '</ul>';
            } else {
                echo $this->messages . PHP_EOL;
            }
        ?>
        </p>
        <p><a href="http://www.filemaker.com/support/product/documentation.html" class="btn">Documentation &raquo;</a></p>
    </div>
    <div class="span4">
        <h2>SimpleFM</h2>
        <p>SimpleFM version <?php echo \Soliant\SimpleFM\Version::VERSION; ?> is installed.</p>
        <p><a href="https://github.com/soliantconsulting/SimpleFM#simplefm-documentation" class="btn">Documentation &raquo;</a></p>
    </div>
    <div class="span3">
        <h2>Zend Framework</h2>
        <p>Zend Framework version <?php echo \Zend\Version\Version::VERSION; ?> is installed.</p>
        <p><a href="http://packages.zendframework.com/docs/latest/manual/en/index.html" class="btn">Documentation &raquo;</a></p>
    </div>
</div>
    <hr>
<div class="row">
    <div class="span12">
<?php if($this->serverIsOnline): ?>
    <h2>Congratulations!</h2>
    <p>You have successfully installed the SimpleFM FMServer Sample application.</p>
<?php else: ?>
    <h2>Install Not Complete</h2>
    <p>Please resolve the Filemaker Server errors.</p>
<?php endif; ?>
    </div>
</div>
